### PR TITLE
Added new community plugins

### PR DESCRIPTION
**Pull request by marcushyett-ph**
This PR adds new community plugins:
* Twilio
* Intercom
* DataBricks
* AWS Kenesis
* Braze

### CODE REVIEW

**Comment by joethreepwood** [comment]
I'll mark Braze as beta in https://github.com/PostHog/posthog.com/pull/3253

**Comment by joethreepwood** [comment]
Just spotted that we're missing the Shopify app from this list btw. Are we adding that in too?

**Comment by marcushyett-ph** [comment]
Good point re Shopify, looking into it

**Comment by marcushyett-ph** [comment]
I'm following up on Shopify it may take a few extra days. Will merge this for now.

**Pull request merged**
